package test;

import umletConverter_class.ConverterUMLet;

public class TestDrive1 {
	public static void main(String[] args) {
		String code = "/**\n"
				+ " * Sample1 クラスは、簡単なIDと名前を持つエンティティを表します。\n"
				+ " */\n"
				+ "public class Sample1 {\n"
				+ "    \n"
				+ "    /**\n"
				+ "     * エンティティのIDを表すフィールド。\n"
				+ "     */\n"
				+ "    private int id;\n"
				+ "    \n"
				+ "    /**\n"
				+ "     * エンティティの名前を表すフィールド。\n"
				+ "     */\n"
				+ "    private String name;\n"
				+ "\n"
				+ "    /**\n"
				+ "     * 指定された ID と名前で新しいエンティティを作成します。\n"
				+ "     *\n"
				+ "     * @param id エンティティのID\n"
				+ "     * @param name エンティティの名前\n"
				+ "     */\n"
				+ "    public Sample1(int id, String name) {\n"
				+ "        this.id = id;\n"
				+ "        this.name = name;\n"
				+ "    }\n"
				+ "\n"
				+ "    /**\n"
				+ "     * エンティティの ID を取得します。\n"
				+ "     *\n"
				+ "     * @return エンティティのID\n"
				+ "     */\n"
				+ "    public int getId() {\n"
				+ "        return id;\n"
				+ "    }\n"
				+ "\n"
				+ "    /**\n"
				+ "     * エンティティの ID を設定します。\n"
				+ "     *\n"
				+ "     * @param id 新しいID\n"
				+ "     */\n"
				+ "    public void setId(int id) {\n"
				+ "        this.id = id;\n"
				+ "    }\n"
				+ "\n"
				+ "    /**\n"
				+ "     * エンティティの名前を取得します。\n"
				+ "     *\n"
				+ "     * @return エンティティの名前\n"
				+ "     */\n"
				+ "    public String getName() {\n"
				+ "        return name;\n"
				+ "    }\n"
				+ "\n"
				+ "    /**\n"
				+ "     * エンティティの名前を設定します。\n"
				+ "     *\n"
				+ "     * @param name 新しい名前\n"
				+ "     */\n"
				+ "    public void setName(String name) {\n"
				+ "        this.name = name;\n"
				+ "    }\n"
				+ "}\n";
		
		ConverterUMLet converter = new ConverterUMLet(code);
		System.out.println(converter.convertCode());
	}
}
