package test;

import umletConverter_class.ConverterUMLet;

public class TestDrive2 {
	public static void main(String[] args) {
		String code = "import java.util.ArrayList;\n"
				+ "import java.util.List;\n"
				+ "\n"
				+ "/**\n"
				+ " * Sample2 クラスは、エンティティをリストで管理するクラスです。\n"
				+ " */\n"
				+ "public class Sample2 {\n"
				+ "\n"
				+ "    /**\n"
				+ "     * 管理対象のエンティティを格納するリスト。\n"
				+ "     */\n"
				+ "    private List<Sample1> entities;\n"
				+ "\n"
				+ "    /**\n"
				+ "     * 新しい Sample2 インスタンスを作成し、エンティティリストを初期化します。\n"
				+ "     */\n"
				+ "    public Sample2() {\n"
				+ "        entities = new ArrayList<>();\n"
				+ "    }\n"
				+ "\n"
				+ "    /**\n"
				+ "     * 指定されたエンティティをリストに追加します。\n"
				+ "     *\n"
				+ "     * @param entity 追加するエンティティ\n"
				+ "     */\n"
				+ "    public void addEntity(Sample1 entity) {\n"
				+ "        entities.add(entity);\n"
				+ "    }\n"
				+ "\n"
				+ "    /**\n"
				+ "     * 指定されたIDを持つエンティティを検索して返します。\n"
				+ "     *\n"
				+ "     * @param id 検索するエンティティのID\n"
				+ "     * @return 見つかったエンティティ、存在しない場合はnull\n"
				+ "     */\n"
				+ "    public Sample1 findEntityById(int id) {\n"
				+ "        for (Sample1 entity : entities) {\n"
				+ "            if (entity.getId() == id) {\n"
				+ "                return entity;\n"
				+ "            }\n"
				+ "        }\n"
				+ "        return null;\n"
				+ "    }\n"
				+ "\n"
				+ "    /**\n"
				+ "     * エンティティリストのサイズを取得します。\n"
				+ "     *\n"
				+ "     * @return エンティティリストのサイズ\n"
				+ "     */\n"
				+ "    public int getEntityCount() {\n"
				+ "        return entities.size();\n"
				+ "    }\n"
				+ "\n"
				+ "    /**\n"
				+ "     * 全てのエンティティを取得します。\n"
				+ "     *\n"
				+ "     * @return エンティティリスト\n"
				+ "     */\n"
				+ "    public List<Sample1> getAllEntities() {\n"
				+ "        return new ArrayList<>(entities);\n"
				+ "    }\n"
				+ "}\n"
				+ "";
		
		ConverterUMLet converter = new ConverterUMLet(code);
		System.out.println(converter.convertCode());
	}
}
